sudo: false
language: python
python:
        - "2.7"
cache:
        directories:
                - $HOME/gcloud/
                - $HOME/.pip-cache

env:
        - GCLOUD=$HOME/gcloud/google-cloud-sdk/bin

before_install:
        #Install gcloud
        - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
                mkdir -p $HOME/gcloud &&
                wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
                cd $HOME/gcloud &&
                tar xzf google-cloud-sdk.tar.gz &&
                printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
                cd $TRAVIS_BUILD_DIR;
          fi

        #Authenticate with gcloud
        - printf -- "$CREDENTIALS_JSON" > $HOME/credentials.json
        - export GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json

install:
        - pip install tox --download-cache $HOME/.pip-cache
        - pip install google-api-python-client --download-cache $HOME/.pip-cache

script:
        - python test/auth_test.py
